name: Checkstyle

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  checkstyle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Run Checkstyle
        uses: dbelyaev/action-checkstyle@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          level: warning               # meldet Verstöße als "warning"
          checkstyle_config: google_checks.xml