# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: mvn -B -N deploy --file pom.xml -DrevisionNumberPlugin.revision=${{ github.run_number }} -DscmBranch=${{ github.ref_name }} -DscmCommit=${{ github.sha }}

    - name: Show run number
      run: |
        echo "Run number is ${{ github.run_number }}"
        echo "ref_name is ${{ github.ref_name }}"
        echo "commit is ${{ github.sha }}"

    - name: Create checkstyle report
      run: mvn -B -N site --file pom.xml -Pcheckstyle

    - name: Upload Checkstyle report
      uses: actions/upload-artifact@v4
      with:
        name: checkstyle-report
        path: target/site

    - name: Check on Error
      run: mvn -B -N validate --file pom.xml -Pcheckstyle

  build-sdk:

    runs-on: ubuntu-latest
    needs: build
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn -B -N deploy --file sdk/pom.xml -DrevisionNumberPlugin.revision=${{ github.run_number }} -DscmBranch=${{ github.ref_name }} -DscmCommit=${{ github.sha }}

  build-sample:

    runs-on: ubuntu-latest
    needs: build-sdk
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn -B deploy --file sample/pom.xml -DrevisionNumberPlugin.revision=${{ github.run_number }} -DscmBranch=${{ github.ref_name }} -DscmCommit=${{ github.sha }}