name: Create Release

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to release from"
        required: true
        default: "main"
      version:
        description: "Release version (e.g. 1.0.0)"
        required: true
      prerelease:
        description: "Is this a prerelease?"
        required: true
        default: "false"

permissions: write-all

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}
          fetch-depth: 0   # wichtig, sonst fehlen Tags für release:prepare

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Run Maven Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          mvn -B release:prepare release:perform --file pom.xml \
            -DreleaseVersion=${{ github.event.inputs.version }} \
            -DdevelopmentVersion=${{ github.event.inputs.version }}-SNAPSHOT \
            -DpushChanges=true

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.version }}
          release_name: Release ${{ github.event.inputs.version }}
          draft: false
          prerelease: ${{ github.event.inputs.prerelease }}



      - name: Upload all JARs
        env:
          UPLOAD_URL: ${{ steps.create_release.outputs.upload_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for file in target/*.jar; do
            echo "Uploading $file ..."
            gh release upload $UPLOAD_URL "$file"
          done


