name: Trivy JAR Scan

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  scan-jar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Extract Maven coordinates (njams-sdk)
        id: extract-maven-coordinates
        run: |
          GROUP_ID=$(mvn help:evaluate -f pom.xml -Dexpression=project.groupId -q -DforceStdout)
          ARTIFACT_ID=$(mvn help:evaluate -f pom.xml -Dexpression=project.artifactId -q -DforceStdout)
          VERSION=$(mvn help:evaluate -f pom.xml -Dexpression=project.version -q -DforceStdout)
          GROUP_PATH=${GROUP_ID//./\/}
          echo "ARTIFACT_ID=$ARTIFACT_ID" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "GROUP_PATH=$GROUP_PATH" >> $GITHUB_ENV

      - name: Build JAR
        run: mvn -B clean package -DskipTests

      - name: Install Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: target/${{ env.ARTIFACT_ID }}-${{  env.VERSION  }}.jar
          format: table
          exit-code: 1   # schlägt fehl, wenn Vulnerabilities gefunden werden
          severity: CRITICAL,HIGH
