name: Trivy JAR Scan

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  scan-jar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Build JAR
        run: mvn -B clean package -DskipTests

      - name: Install Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: target/actiontest-1.24-SNAPSHOT.jar
          format: table
          exit-code: 1   # schlägt fehl, wenn Vulnerabilities gefunden werden
          severity: CRITICAL,HIGH
